# Generated by Django 5.2.8 on 2025-11-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightmodel',
            name='flight_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
