# Generated by Django 5.2.8 on 2025-11-22 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_flightmodel_flight_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('adhaar', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.seatclass')),
            ],
        ),
    ]
