# Generated by Django 5.2.8 on 2025-11-22 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_seatclass_passengerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdetail',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.flightmodel'),
            preserve_default=False,
        ),
    ]
