# Generated by Django 5.2.8 on 2026-01-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_passengerdetail_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdetail',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
