# Generated by Django 5.2.8 on 2026-01-31 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_passengerdetail_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passengerdetail',
            unique_together={('flight', 'seat_class', 'seat_number')},
        ),
    ]
